<html>
	<head>
		<title>Bob's Auto Parts </title>
		<style type = "text/css">
			h1 {color:white; font-size:24pt; text-align:center;
				font-family:arial,sans-serif; font-weight:bold}
			.menu {color:white; font-size:12pt; text-align:center;
				font-family:arial,sans-serif; font-weight:bold}
			td {background:skyblue}
			p {color:black; font-size:12pt; text-align:justify;
				font-family:arial,sans-serif}
			p.foot {color:white; font-size:9pt; text-align:center;
				font-family:arial,sans-serif; font-weight:bold}
			a:link,a:visited,a:active {color:white}
		</style>
	</head>
	
	<body>
		<!-- Page footer -->
		<table width="100%" bgcolor="black" cellpadding="12" border="0">
			<tr>
				<td>
					<p class = "foot">&copy; Bob's Auto Parts Pvt. Ltd.</p>
					<p calss = "foot">Please see our
						<a href="legal.php">legal information page</a>
					</p>
				</td>
			</tr>
		</table>	
	</body>
</html>