<html>
	<head>
		<title>Bob's Auto Parts </title>
		<style type = "text/css">
			h1 {color:white; font-size:24pt; text-align:center;
				font-family:arial,sans-serif; font-weight:bold}
			.menu {color:white; font-size:12pt; text-align:center;
				font-family:arial,sans-serif; font-weight:bold}
			 td {background:skyblue}
			p {color:black; font-size:12pt; text-align:justify;
				font-family:arial,sans-serif}
			p.foot {color:white; font-size:9pt; text-align:center;
				font-family:arial,sans-serif; font-weight:bold}
			a:link,a:visited,a:active {color:white}
		</style>
	</head>
	
	<body>
		<!-- page header -->
		
		<table width="100%" bgcolor="black" cellpadding="12" cellspacing="0" border="0">
			<tr bgcolor="black">
			
				<td align="left"><img src="logo.jpg" alt="BAP logo" height="70" width="70">
				</td>
				<td>
					<h1><font color = "#2f4f4f">Bob's Auto Parts</font></h1>
				</td>
				
				<td align="right"><img src="logo.jpg" alt="BAP logo" height="70" width="70">
				</td>
			</tr>
			
		</table>
		
		
		<!--menu-->
		
		<table width = "100%" bgcolor="white" cellpadding="4" cellspacing = "4">
			<tr>
				<td width = "25%">
					<img src="logo.jpg" alt="" height="20" width="20">
					<a href="home.php">
					<span class ="menu">Home</span>
					</a>
					
				</td>
				<td width = "25%">
					<img src="logo.jpg" alt="" height="20" width="20">
					<a href="orderform.php">
					<span class ="menu">Place an order</span>
					<a>
				</td>
				<td width = "25%">
					<img src="logo.jpg" alt="" height="20" width="20">
					<a href="services.php">
					<span class ="menu">Services</span>
					</a>
				</td>
				<td width = "25%">
					<img src="logo.jpg" alt="" height="20" width="20">
					<a href="contact.php">
					<span class ="menu">Contact us</span>
					</a>
				</td>
			</tr>
			</b>
		</table>
		
		<!-- Page Content 
		
		<p>Welcome to the store of Bob.</p>
		<p>We are specialize in serving your business needs
			and hope to hear from you soon.</p> 
			
		<!-- Page footer
		<table width="100%" bgcolor="black" cellpadding="12" border="0">
			<tr>
				<td>
					<p class = "foot">&copy; Bob's Auto Parts Pvt. Ltd.</p>
					<p calss = "foot">Please see our
						<a href="legal.php">legal information page</a>
					</p>
				</td>
			</tr>
		</table> 	-->
	</body>
</html>